Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2021-12, with the labels that each got.

#488 Reduce usages of Guava
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
Labels: maintenance, chore

#489 Adding test of serial form of `program.dat` including pickles
  Jenkinsfile
  pom.xml
  src/test/java/org/jenkinsci/plugins/workflow/cps/SerialFormTest.java
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence-workspace/p/running
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence-workspace/p@tmp/durable-dae459c1/jenkins-log.txt
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence-workspace/p@tmp/durable-dae459c1/jenkins-result.txt
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence-workspace/p@tmp/durable-dae459c1/script.sh
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/build.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/log
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/log-index
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/program.dat
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/workflow/2.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/workflow/3.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/workflow/4.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/1/workflow/5.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/legacyIds
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/builds/permalinks
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/config.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/jobs/p/nextBuildNumber
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/nodes/remote/config.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/org.jenkinsci.plugins.workflow.flow.FlowExecutionList.xml
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/secrets/jenkins.slaves.JnlpSlaveAgentProtocol.secret
  src/test/resources/org/jenkinsci/plugins/workflow/cps/SerialFormTest/persistence/secrets/master.key
Labels: tests

#356 Test case for JENKINS-57253
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
Labels: tests

#492 [JENKINS-67380] Detect oversized maps, collections and arrays and truncate
  src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
Labels: bug

#490 Avoid printing warnings from `CpsStepContext.completed`
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
Labels: enhancement

#493 Exclude `javax.servlet:servlet-api`
  pom.xml
Labels: bug

#494 remove badges from readme
  README.md
Labels: documentation
