Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2021-11, with the labels that each got.

#475 Incorrect use of `gitHubRepo`
  pom.xml
Labels: bug

#474 enable cd
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: internal

#476 `Jenkinsfile` cleanups
  Jenkinsfile
Labels: internal

#478 No need to override `reuseForks`
  pom.xml
Labels: tests

#480 Verifying that a missing `program.dat` causes a comprehensible error
  src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java
Labels: tests

#482 Update Dependabot configuration
  .github/dependabot.yml
Labels: maintenance, chore

#484 Remove version from `Jenkinsfile`
  Jenkinsfile
Labels: maintenance

#487 Ensure compatibility with Guava 31+
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java
Labels: internal

#481 Allow Jenkins to override icons on newer versions
  src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/cps/PauseUnpauseAction/action.jelly
  src/main/webapp/images/24x24/README.md
  src/main/webapp/images/24x24/pause.png
  src/main/webapp/images/pause.svg
Labels: enhancement
