Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2022-11, with the labels that each got.

#604 Update a few frontend dependencies
  .github/dependabot.yml
  README.md
  package.json
  yarn.lock
Labels: dependencies

#605 Fix dependabot ecosystem
  .github/dependabot.yml
Labels: chore

#603 Bump plugin from 4.48 to 4.49
  pom.xml
Labels: dependencies

#611 Update plugin BOM and remove unnecessary version specifications in pom.xml
  pom.xml
Labels: dependencies

#596 Robustness of `CpsFlowExecution.getNode`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: bug

#613 [JENKINS-46163] Add support for spread and spread-map operators
  lib/src/main/java/com/cloudbees/groovy/cps/Builder.java
  lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/ListBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/SpreadBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/SpreadMapBlock.java
  lib/src/test/java/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.java
Labels: enhancement

#614 Convert GStringImpl to String in the RHS of CPS-transformed method pointers
  lib/src/main/java/com/cloudbees/groovy/cps/impl/MethodPointerBlock.java
  lib/src/test/java/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.java
Labels: bug

#621 Make Dependabot ignore Groovy and do not specify explicit remoting version in groovy-cps-dgm-builder
  .github/dependabot.yml
  dgm-builder/pom.xml
  pom.xml
Labels: dependencies

#615 Miscellaneous code cleanup
  dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Driver.java
  dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Translator.java
  lib/src/main/java/com/cloudbees/groovy/cps/Block.java
  lib/src/main/java/com/cloudbees/groovy/cps/Builder.java
  lib/src/main/java/com/cloudbees/groovy/cps/Continuable.java
  lib/src/main/java/com/cloudbees/groovy/cps/Continuation.java
  lib/src/main/java/com/cloudbees/groovy/cps/CpsTransformer.java
  lib/src/main/java/com/cloudbees/groovy/cps/DepthTrackingEnv.java
  lib/src/main/java/com/cloudbees/groovy/cps/Next.java
  lib/src/main/java/com/cloudbees/groovy/cps/Outcome.java
  lib/src/main/java/com/cloudbees/groovy/cps/TransformerConfiguration.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/BlockScopeEnv.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/CallEnv.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/Caller.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/ClosureCallEnv.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/DoWhileBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallEnv.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/IfBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/LogicalOpBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/MethodPointerBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/NotBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/SuspendBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/ThrowBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/TryBlockEnv.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/VariableDeclBlock.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsDefaultGroovyMethodsTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/VariableDeclarationTest.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java
Labels: chore

#632 Remove unnecessary SpotBugs exclusions
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
Labels: chore
