Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2022-07, with the labels that each got.

#549 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#544 [JENKINS-68610] Re-enable admin auto approval when job config submitted via CLI/REST
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionTest.java
Labels: bug

#559 Update icons to new symbol icon api
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
  src/main/resources/images/symbols/pause.svg
  src/main/resources/images/symbols/redo.svg
  src/main/resources/org/jenkinsci/plugins/workflow/cps/PauseUnpauseAction/action.jelly
  src/main/webapp/images/pause.svg
Labels: enhancement

#564 BOM updates
  pom.xml
Labels: dependencies

#570 [JENKINS-49707] Implement `BodyExecution.cancel(Throwable)`
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java
Labels: bug
