Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2022-12, with the labels that each got.

#635 Require Java 11 or newer
  dgm-builder/pom.xml
  dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Driver.java
  dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Translator.java
  lib/src/main/java/com/cloudbees/groovy/cps/Builder.java
  lib/src/main/java/com/cloudbees/groovy/cps/Continuable.java
  lib/src/main/java/com/cloudbees/groovy/cps/Next.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/CastBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/ContinuationGroup.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/FunctionCallBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/SuspendBlock.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/ThrowBlock.java
  lib/src/test/java/com/cloudbees/groovy/cps/BasicTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsDefaultGroovyMethodsTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsStringGroovyMethodsTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/impl/FunctionCallBlockTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/impl/ThrowBlockTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/impl/TryCatchBlockTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.java
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyInvoker.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GlobalVariable.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImpl.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/nodes/StepEndNode.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/IteratorHack.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayFlowFactoryAction.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/DynamicEnvironmentExpanderTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuableTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/AmbiguousEchoLowerStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/AmbiguousEchoUpperStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/EchoResultStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/EchoStringAndDoubleStep.java
  pom.xml
Labels: chore

#641 Update doc/persistence.md
  doc/persistence.md
Labels: documentation

#640 [JENKINS-70108] CastBlock must contextualize invoker to avoid issues in mixed-trust scenarios
  lib/src/main/java/com/cloudbees/groovy/cps/Builder.java
  lib/src/main/java/com/cloudbees/groovy/cps/impl/CastBlock.java
  lib/src/test/java/com/cloudbees/groovy/cps/AbstractGroovyCpsTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/sandbox/SandboxInvokerTest.java
Labels: bug

#644 Add Java 17 to build matrix
  Jenkinsfile
Labels: tests
