Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2022-03, with the labels that each got.

#510 Record which `program.dat` is being saved in a thread dump
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
Labels: enhancement

#512 Update plugin parent POM and plugin BOM
  pom.xml
  src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java
Labels: dependencies

#499 Add *.log to gitignore
  .gitignore
Labels: chore

#514 Update some JS deps
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: dependencies

#472 Deprecated assertions and calls to IOUtils replaced
  src/main/java/org/jenkinsci/plugins/workflow/cps/BodyReference.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyInvoker.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScript.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmThreadOnly.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySample.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/persistence/PersistIn.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayPipelineCommand.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
  src/main/java/org/jenkinsci/plugins/workflow/cps/view/InterpolatedSecretsAction.java
  src/test/java/org/jenkinsci/plugins/workflow/WorkflowJobNonRestartingTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/ContextVariableSetTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionValidatorTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionMemoryTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpActionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuableTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java
Labels: chore

#515 [JENKINS-68071] Java 17 compat: make `CpsThreadGroup.paused` `transient` to avoid XStreaming `AtomicBoolean`
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
Labels: bug

#517 Update plugin parent POM and BOM
  pom.xml
Labels: dependencies

#518 [JENKINS-68092] Serialization of `java.util.concurrent` data structure in Pipeline: Groovy
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
Labels: bug

#519 Use a concurrent map to manage timings
  src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: bug
