Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2023-09, with the labels that each got.

#780 [JENKINS-71692] Attempt to stop step executions if the CPS VM thread dies with a fatal error
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: bug

#784 Remove flaky assertion from `FlowDurabilityTest.verifyExecutionRemoved`
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java
Labels: developer

#787 Delete unnecessary test
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/ParamsVariableTest.java
Labels: tests

#791 Use controller-wide default XStream driver where possible
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
Labels: developer

#769 Support system themes for Pipeline editor
  plugin/package.json
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/view/ThemeUtil.java
  plugin/src/main/js/workflow-editor.js
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/config.jelly
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/editor/workflow-editor.jelly
Labels: enhancement
