Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2023-06, with the labels that each got.

#723 Require Jenkins 2.387.3 or newer
  plugin/pom.xml
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/SnippetizerTester.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java
  pom.xml
Labels: developer

#732 Restore missing `<scope>test</scope>` to `git`
  plugin/pom.xml
Labels: bug

#702 Replace Prototype.js with native JavaScript
  plugin/src/main/js/samples.js
  plugin/src/main/js/workflow-editor.js
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
Labels: bug

#733 Fix lint
  plugin/src/main/js/samples.js
  plugin/src/main/js/workflow-editor.js
Labels: chore
