Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2023-07, with the labels that each got.

#743 Adapt 'one-column' design in thread dump
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly
Labels: enhancement

#749 Remove usages of Prototype from Steps Reference
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/workflow.js
Labels: bug

#718 Drop support for ancient web browsers
  plugin/.eslintrc.js
  plugin/package.json
  plugin/src/main/js/workflow-editor.js
  plugin/yarn.lock
Labels: bug

#674 Fix generated gdsl code display names
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/gdsl.groovy
Labels: bug

#755 `…/threadDump/program.xml` hangs when program still loading pickles
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDump.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly
Labels: bug

#756 Remove unnecessary workarounds
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: chore

#757 Assertion error from `CpsThread.getStackTrace`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
Labels: bug
