Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2023-10, with the labels that each got.

#796 Added `@Deprecated` where `@deprecated` already in Javadoc
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowFactoryAction.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/SingleJobTestBase.java
Labels: chore

#797 `RejectedExecutionException` from `CpsFlowExecution.getCurrentExecutions`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: bug

#801 Test with Jdk21
  Jenkinsfile
Labels: chore

#809 [JENKINS-50407] Better diagnosis for certain fatal loading errors
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: bug

#807 Migrate `FlowNode` storage to `BulkFlowNodeStorage` upon execution completion to improve read performance
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/PersistenceProblemsTest.java
Labels: enhancement
