Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2023-08, with the labels that each got.

#758 `CpsFlowExecution.suspendAll` could log ISE
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: bug

#759 [JENKINS-59743] Restarting before `afterStepExecutionsResumed` could leave a build paused
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: bug

#761 Avoid `javax` imports in Groovy views
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/globals.groovy
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/html.groovy
Labels: developer

#765 [JENKINS-71818] `CpsTransformerTest` fails on Java 21
  lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
Labels: internal

#766 Honoring termination milestones
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: bug

#228 Record internal calls to what look like Jenkins APIs made during the course of Pipeline builds
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/LoggingInvokerTest.java
Labels: enhancement

#767 NPE related to `internalCalls`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: bug

#768 Switch from `RUN_SCRIPTS` to `ADMINISTER`
  doc/classloader.md
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction/index.jelly
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayActionTest.java
Labels: chore

#773 Avoid `FlowExecutionOwner.get` from `PipelineInternalCalls`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: bug
