Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2023-12, with the labels that each got.

#341 [JENKINS-38669] (2/3) `CpsScmFlowDefinition.getSCMs`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
Labels: bug

#821 Suppress ESLint warning `no-unused-vars`
  plugin/src/main/js/workflow-editor.js
Labels: chore

#666 [JENKINS-70695] add copy to clipboard button for snippet generator
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/handle-prototype.js
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
Labels: enhancement
