Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2024-07, with the labels that each got.

#900 Refine interface of Pipeline Syntax
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/sidepanel.jelly
Labels: ui

#909 Update to 2.426.x, simplify JSON parsing
  plugin/pom.xml
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/handle-prototype.js
  pom.xml
Labels: dependencies

#907 [JENKINS-73470] Option to hide "Use Groovy Sandbox"
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/config/CPSConfiguration.java
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition/config.jelly
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/config/CPSConfiguration/config.jelly
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/config/CPSConfiguration/help-hideSandbox.html
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionTest.java
Labels: enhancement
