Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2024-01, with the labels that each got.

#538 Remove `default-allowlist` entries for Groovy source files related to Declarative
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist.java
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist/default-allowlist
Labels: developer

#826 Throw an exception when trying to save actions for a `FlowNode` for a completed execution
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: developer

#828 Revert "Merge pull request #538 from dwnusbaum/post-SECURITY-359"
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist.java
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist/default-allowlist
Labels: bug

#833 Suppress warnings for spotbugs 4.8.3
  lib/src/main/java/com/cloudbees/groovy/cps/impl/NotBlock.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  pom.xml
Labels: dependencies

#830 Forward compatibility with Guice 7
  plugin/pom.xml
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java
  pom.xml
Labels: dependencies

#834 Fix deprecations, avoid `@Inject`
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStep.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/LoadStepExecution.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/ContextVariableSetTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition2Test.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/RestartingLoadStepTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/CurveMetaStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicListWithSymbolStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/MonomorphicWithSymbolStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/StateMetaStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/testMetaStep/chemical/DetectionMetaStep.java
Labels: dependencies
