Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2024-04, with the labels that each got.

#877 More efficient use of `GroovyCategorySupport`
  lib/src/main/java/com/cloudbees/groovy/cps/Continuable.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsDefaultGroovyMethodsTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/CpsTransformerTest.java
  lib/src/test/java/com/cloudbees/groovy/cps/impl/NotBlockTest.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/SandboxContinuable.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionMemoryTest.java
Labels: enhancement

#880 Override 'getIconFileName' rather than setting 'getIconClassName'
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
Labels: chore

#882 Support Maven reproducible builds
  dgm-builder/src/main/java/com/cloudbees/groovy/cps/tool/Translator.java
Labels: developer
