Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2024-08, with the labels that each got.

#914 Assert `@Exported` form of `EnvActionImpl`
  plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
Labels: tests

#901 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#915 Removing stock security scan based on Java 11
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#917 Enable Jenkins Security Scan and bypass CodeQL's JavaCompiler to support JDK 17+
  .github/workflows/jenkins-security-scan.yml
  lib/pom.xml
Labels: maintenance

#916 Improve support bundle data for running Pipelines, update support bundle component names and file paths, and update log warning for a particular type of error during step completion
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
Labels: enhancement

#925 Clear `CpsBodyExecution.thread`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStep.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
Labels: bug

#929 False positives from `LoggingInvoker.isInternal`
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/IgnoredInternalClasses.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/LoggingInvokerTest.java
Labels: bug

#922 Remove `subversion` test dep
  plugin/pom.xml
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinitionTest.java
Labels: dependencies
