Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2024-10, with the labels that each got.

#944 Avoid holding locks from `croak` when calling `notifyListeners`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadGroup.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java
Labels: bug

#945 `CpsFlowExecutionTest.iterateAfterSuspend` flaky
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: tests

#948 JENKINS-73941 - Option to hide "Use Groovy Sandbox" for users without Administer permission globally in the system
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/config/CPSConfiguration.java
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/config/CPSConfiguration/config.jelly
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/config/CPSConfiguration/help-hideSandbox.html
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/JcascTest.java
  plugin/src/test/resources/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinitionTest/cpsLoadConfiguration/org.jenkinsci.plugins.workflow.cps.config.CPSConfiguration.xml
  plugin/src/test/resources/org/jenkinsci/plugins/workflow/cps/casc_test.yaml
  plugin/src/test/resources/org/jenkinsci/plugins/workflow/cps/casc_test_expected.yaml
Labels: developer
