Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2025-07, with the labels that each got.

#1061 Prevent `NullPointerException` in `CpsBodyExecution.FailureAdapter`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodySubContext.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThread.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
Labels: bug

#1052 Notify `GraphListener` extensions prior to listeners added via `FlowExecution.addListener`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/FlowHead.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/GraphListenerTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecutionTest.java
Labels: developer

#1066 Migrate from Commons Lang 2 to Commons Lang 3
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/DSL.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/GroovySourceFileAllowlist.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/SingleJobTestBase.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/FlowDurabilityTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/actions/ArgumentsActionImplTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/nodes/StepNodeTest.java
Labels: internal
