Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2025-08, with the labels that each got.

#1068 Remove call stack from `runInCpsVmThread`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: bug

#1071 Improved logging in `CpsStepContext`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
Labels: enhancement

#1072 Better `CpsBodySubContext.toString`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsBodySubContext.java
Labels: internal

#1075 Enable strict bundled artifact checks
  plugin/pom.xml
  pom.xml
Labels: internal
