Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2025-04, with the labels that each got.

#1009 Deleting `SerializationTest.persistEphemeralObject`
  plugin/src/test/java/org/jenkinsci/plugins/workflow/SerializationTest.java
Labels: tests

#1011 Dependabot groups take 2
  .github/dependabot.yml
Labels: internal

#935 Configure eslint for warnings-ng to report on CI
  .gitignore
  plugin/package.json
  plugin/pom.xml
  plugin/yarn.lock
Labels: chore

#1020 Upgrade to yarn 4.x
  plugin/.mvn_exec_yarn_corepack
  plugin/.yarnrc.yml
  plugin/package.json
  plugin/pom.xml
  plugin/yarn.lock
  pom.xml
Labels: dependencies

#1022 `suspendAll` should not wait for `programPromise`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
Labels: bug
