Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2025-02, with the labels that each got.

#980 Migrate from EE 8 to EE 9 in Groovy view
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/globals.groovy
Labels: internal

#986 `WorkflowTest.env` failure
  plugin/pom.xml
  plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
Labels: tests

#992 Override `CallEnv.toString`
  lib/src/main/java/com/cloudbees/groovy/cps/impl/CallEnv.java
Labels: chore

#994 Warn user when forgetting `def` on a variable
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Messages.properties
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorServiceTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/DSLTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayPipelineCommandTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/steps/ParallelStepTest.java
Labels: enhancement

#995 [JENKINS-75353] Ignore `Closure` metaproperties
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/LoggingInvokerTest.java
Labels: bug
