Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2025-01, with the labels that each got.

#966 [JENKINS-75067] Unexport step bodies when completed in synchronous mode
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsStepContext.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsStepContextTest.java
Labels: bug

#968 Persist `ReplayFlowFactoryAction#sandbox`
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayFlowFactoryAction.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/Workflow2Test.java
Labels: bug

#972 Migrate from EE 8 to EE 9
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsScmFlowDefinition.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsThreadDumpAction.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/Snippetizer.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/SnippetizerLink.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/replay/ReplayAction.java
  pom.xml
Labels: dependencies

#974 Using `StepExecution.acceptAll`
  plugin/pom.xml
  plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/CpsBodyExecutionTest.java
Labels: chore
