Repository jenkinsci/workflow-cps-plugin, pull requests merged in 2025-03, with the labels that each got.

#996 Flake in `Workflow2Test`
  plugin/src/test/java/org/jenkinsci/plugins/workflow/Workflow2Test.java
Labels: developer

#997 [JENKINS-75361] Consider `Closure.resolveStrategy` to reduce false positives
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/cps/LoggingInvokerTest.java
Labels: bug

#1002 Updated to `FlowExecution.getAuthentication2`
  plugin/pom.xml
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsFlowExecution.java
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/CpsVmExecutorService.java
  plugin/src/test/java/org/jenkinsci/plugins/workflow/WorkflowTest.java
Labels: developer

#1003 [JENKINS-75447] Fix Snippetizer rendering of "properties" step
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/cps/Snippetizer/index.jelly
Labels: bug

#1005 Ignore `__model__*` variables generated by Declarative in script splitting mode
  plugin/src/main/java/org/jenkinsci/plugins/workflow/cps/LoggingInvoker.java
Labels: bug

#946 Update appearance of editor
  plugin/src/main/js/workflow-editor.js
  plugin/src/main/less/workflow-editor.less
  plugin/src/main/resources/org/jenkinsci/plugins/workflow/editor/workflow-editor.jelly
Labels: enhancement
